### ISSUE TITLE
use the model from tensorflow

### ISSUE THREAD

**Issue by devMls** [itaicaspi/SVHN-Multi-Digit-torch#1]
hi, is possible migrate this model to use it with tensorflow?

**Comment by itaicaspi** [comment]
Hi, there's no simple way that I know of

**Comment by mathetes87** [comment]
Torch uses Dynamic Computation Graphs whereas Tensorflow does not and this made it impossible to migrate this particular model. Recently Fold was released for Tensorflow, though it doesn't seem easy to migrate to.
