### ISSUE TITLE
deploy in vps

### ISSUE THREAD

**Issue by devMls** [itaicaspi/SVHN-Multi-Digit-torch#2]
Hi i have another dude.

is mandatory use cuda?

i want to deploy this in a vps and install cuda in the vps is posble to be troubeling

**Comment by itaicaspi** [comment]
It's not mandatory to use cuda. Use the type flag in the arguments to turn it off

**Comment by devMls** [comment]
thanks por the response, but i still not sure about how to use this parameter,, in my computer i desinstall cutorch for reproduce the escenario and after that, remove the require cutorch of the eval script.

then i try different values in the -type argument but nothing work, i can only execute with the cutorch installed

is possile that the root cause is because in the line 40 of eval.lua have this instruction input = input:cuda()
???
this is the output:
File.lua:343: unknown Torch class <torch.CudaTensor>
stack traceback:
	[C]: in function 'error'
	/home/miguel/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	/home/miguel/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/miguel/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/miguel/torch/install/share/lua/5.1/nn/Module.lua:184: in function 'read'
	/home/miguel/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/miguel/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	eval.lua:26: in main chunk
	[C]: in function 'dofile'
	...guel/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

**Comment by devMls** [comment]
is possile that the root cause is because in the line 40 of eval.lua have this instruction input = input:cuda()
???
